//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapplication8
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ganEntities2 : DbContext
    {
        public ganEntities2()
            : base("name=ganEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<assignment> assignments { get; set; }
        public virtual DbSet<Rolemaster> Rolemasters { get; set; }
        public virtual DbSet<Signup> Signups { get; set; }
        public virtual DbSet<tblogin> tblogins { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
    }
}
