//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Signup
    {
        public int id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<int> ROLEID { get; set; }
        public string RoleName { get; set; }
    }
}
